[project]
name = "libre"
description = "Algorithmic stablecoin system built on Stacks"
authors = ["Your Name <your.email@example.com>"]
telemetry = false
cache_dir = "./.cache"

[contracts.libre]
path = "contracts/libre.clar"

[contracts.price-oracle]
path = "contracts/price-oracle.clar"

[contracts.rebase-controller]
path = "contracts/rebase-controller.clar"

[contracts.staking-pool]
path = "contracts/staking-pool.clar"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More information: https://www.hiro.so/blog/new-safety-checks-in-clarinet